server:
  port: 9091
  servlet:
    context-path: /
spring:
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_dingcan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 920521
  #将数据库的时间格式化
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8


#mybatis-plush配置
mybatis-plus:
  type-aliases-package: top.dc.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    top.dc.mapper: debug
